### ISSUE TITLE
Thanks for sharing this

### ISSUE THREAD

**Issue by idkjs** [phated/twentyfive-stars#8]
Your [Setting up Auth0](./docs/setting-up-auth0.md) write was simply beautiful. The care you took there is much appreciated from someone who dreads setting up `auth` on AuthO. Thank you, sir.

Now lets see if it works!

**Comment by phated** [comment]
@idkjs No problem! I mostly wrote that document for "future blaine" that will need to run this server and completely forget how to set up the auth.

I've not fully vetted it to make sure I was doing everything correctly, but I spent a lot of time hacking on it.

I'd also warn against leaning too heavily into this project because async-graphql is completely changing in the upcoming 2.0 (work here stalled because there were a bunch of problems with the design choices of that library). I know sqlx was changing a bunch too but haven't kept up. 

In addition, the card game this was written for was cancelled. If I work on this again, it will be warped into something completely different.

**Comment by idkjs** [comment]
And yet, this has been immensly helpful for `rust` generally, `rust + graphql` and for `AuthO` set up. Not leaning on it, just learning and in that case this has been perfect as is. Plus learned about `grain` rummaging through your github to see what else I might learn. Thanks again, sir. Keep up the sharing and teaching!
